version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: message-broker
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_VHOST: CAP
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq
      - ./.docker/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - default

  mssql-server:
    image: microsoft/mssql-server-linux:latest
    container_name: data-base
    hostname: mssql-server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Admin@123
      - CHECK_POLICY=OFF
    volumes:
      - ./.docker/mssql/data/:/var/opt/mssql/data
    networks:
      - default

networks:
  default:
    name: cap-eventbus
    driver: bridge
